name: Build g3man

on:
  push:
    branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest, artifact-name: g3man-ubuntu-amd64 }
          - { os: windows-latest, artifact-name: g3man-windows-amd64 }

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install MSYS2
        id: msys2
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2.30.0
        with:
          msystem: MINGW64
          update: false
          cache: true
          install: >-
            mingw-w64-x86_64-libadwaita
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-ninja
            
      - name: Compile C Libraries
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
            cd c
            sh build.sh

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12' 

      - name: Publish
        env:
          MINGWROOT: ${{ steps.msys2.outputs.msys2-location }}\mingw64
        run: |
          cd g3man/Publishing
          python3 publish.py
          ls -R ../..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix['artifact-name'] }}
          path: g3man/Publishing/package
